"""Add config_json to IntegrationConnection

Revision ID: 564efb5ef432
Revises: 20260622_01
Create Date: 2026-06-25 19:32:14.033809
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

revision: str = '564efb5ef432'
down_revision: Union[str, None] = '20260622_01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('integration_connections', sa.Column('config_json', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('integration_connections', 'config_json')
    # ### end Alembic commands ###
